const siteMetadata = {
  robots: `index, follow`,
  title: `Seller Terminal - Your Amazon Reimubursemnets Case Advocate!`,
  description: `Join 1000+ sellers, brand owners, and warehouses who recovered their money with our reimbursement recovery services. Get your first $500 for free.`,
  keywords: `Amazon Seller Reimbursement Services, Automated Amazon Seller Reporting, FBA overcharged fees, Amazon FBA audit, FBA auditor, Amazon seller refunds, Lost inventory reimbursement`,
  siteUrl: `https://sellerterminal.com/`,
  httpEquiv: `en-us`,
};

/**
 * @type {import('gatsby').GatsbyConfig}
 */
module.exports = {
  siteMetadata,
  plugins: [
    `gatsby-plugin-image`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/assets/svgs`,
      },
    },
    'gatsby-plugin-sitemap',
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    "gatsby-plugin-styled-components",
    `gatsby-plugin-offline`,
    'gatsby-plugin-preload-fonts',
    'gatsby-plugin-react-helmet',
    {
      resolve: 'gatsby-plugin-brotli',
      options: {
        extensions: ['css', 'html', 'js', 'svg'],
      },
    },
    {
      resolve: `gatsby-plugin-postcss`,
      options: {
        postCssPlugins: [
          require('cssnano')({
            preset: 'default',
          }),
        ],
      },
    },
    {
      resolve: `gatsby-plugin-purgecss`,
      options: {
        printRejected: true,
        tailwind: false,
        develop: false,
        purgeCSSOptions: {
          content: [`${__dirname}/src/**/**/*.js`],
          safelist: [
            /col-(xs|sm|md|lg|xl|xxl)-\d+/,
            /offset-(xs|sm|md|lg|xl|xxl)-\d+/,
            /col-\d+/, 
            /row/,
            /container/,
            /btn/,
            /navbar/,
            /navbar-(light|dark)/,
            /navbar-(expand)-(sm|md|lg|xl|xxl)/,
            /navbar-brand/,
            /navbar-toggler/,
            /navbar-toggler-icon/,
            /collapsed/,
            /nav/,
            /nav-item/,
            /nav-link/,
            /nav-tabs/,
            /active/,
            /tab-content/,
            /active/,
            /tab-pane/,
            /fade/,
            /show/,
            /collapse/,
            /show/,
            /m[trblxy]?-\d+/,
            /p[trblxy]?-\d+/,
            /m[trblxy]?-(auto|0)/,
            /p[trblxy]?-(auto|0)/,
            /m[trblxy]?-(1|2|3|4|5|6)/,
            /p[trblxy]?-(1|2|3|4|5|6)/,
            /m[trblxy]?-(sm|md|lg|xl)/,
            /p[trblxy]?-(sm|md|lg|xl)/,
            /g-(sm|md|lg|xl|xxl)-\d+/,
            /d-(none|inline|inline-block|block|grid|table|table-row|table-cell|flex|inline-flex)/,
            /d-(xs|sm|md|lg|xl|xxl)-(none|inline|inline-block|block|grid|table|table-row|table-cell|flex|inline-flex)/,
            /slick-/,
            /slick-slider/,
            /slick-track/,
            /slick-list/,
            /slick-initialized/,
            /accordion/,
            /accordion-button/,
            /accordion-header/,
            /accordion-item/,
            /dropdown/,
            /dropdown-menu/,
            /dropdown-item/,
            /dropdown-toggle/,
            /show/,
            /dropend/,
            /dropstart/,
            /dropleft/,
            /dropright/,
            /EZDrawer/
          ],
        },
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Seller Terminal - Your Amazon Reimubursemnets Case Advocate!`,
        short_name: `Seller Terminal`,
        start_url: `/`,
        background_color: `#f7f0eb`,
        theme_color: `#a2466c`,
        display: `standalone`,
        icon: `${__dirname}/static/favicon.png`,
      },
    },
    {
      resolve: "gatsby-plugin-react-svg",
      options: {
        rule: {
          include: /svgs/,
        },
      },
    },
    {
      resolve: "gatsby-plugin-robots-txt",
      options: {
        host: `${siteMetadata.siteUrl}`,
        sitemap: `${siteMetadata.siteUrl}sitemap-index.xml`,
        policy: [
          { userAgent: "*", disallow: ["/cgi-bin/", "/wp-admin/"] },
          { userAgent: "Googlebot", allow: "/" },
          { userAgent: "googlebot-image", allow: "/" },
          { userAgent: "googlebot-mobile", allow: "/" },
          { userAgent: "Googlebot-News", allow: "/" },
          { userAgent: "Googlebot-Video/1.0", allow: "/" },
          { userAgent: "APIs-Google", allow: "/" },
          { userAgent: "Googlebot-Image/1.0", allow: "/" },
          { userAgent: "MSNBot", disallow: "" },
          { userAgent: "Slurp", disallow: "" },
          { userAgent: "Teoma", disallow: "" },
          { userAgent: "Gigabot", disallow: "" },
          { userAgent: "Robozilla", disallow: "" },
          { userAgent: "Nutch", disallow: "" },
          { userAgent: "ia_archiver", disallow: "" },
          { userAgent: "baiduspider", disallow: "" },
          { userAgent: "naverbot", disallow: "" },
          { userAgent: "yeti", disallow: "" },
          { userAgent: "yahoo-mmcrawler", disallow: "" },
          { userAgent: "psbot", disallow: "" },
          { userAgent: "yahoo-blogs/v3.9", disallow: "" },
        ],
      },
    },
  ],
}
